name: Check Forex and Email me
#on: [push]
on:
  schedule:
    # Use POSIX cron syntax (minute hour day_of_month month day_of_week)
    - cron: '10 19 * * *'

  # Allows manual triggering of the workflow from the Actions tab (optional)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install resend 
        
      - name: Run forex.py
        # Expose the GitHub Actions secret as an environment variable named 'ACCESS_KEY'
        # remember to add secrets in Github Actions Web UI
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: python forex.py
